# When you use this template, you must change this name field.
name: tobe

environment:
  sdk: 3.6.0

workspace:
  - app/backend
  - app/catalog
  - app/mobile
  - core/analytics
  - core/analytics_firebase
  - core/authenticator
  - core/common
  - core/data
  - core/database
  - core/database_isar
  - core/datastore
  - core/designsystem
  - core/domain
  - core/model
  - core/network
  - core/network_model
  - core/testing
  - core/ui
  - feature/auth
  - feature/debug
  - feature/feed
  - feature/home
  - feature/onboarding
  - feature/quest
  - feature/settings

dev_dependencies:
  melos: 6.3.0
  yumemi_lints: 2.2.0

dependency_overrides:
  collection: 1.19.1
  file: 7.0.0
  intl: 0.20.1
  meta: 1.15.0
  test_api: 0.7.4
  web: 0.4.2
