name: feature_onboarding
description: "This package provides onboarding features."
publish_to: "none"

environment:
  sdk: 3.6.0
  flutter: 3.27.1

resolution: workspace

dependencies:
  core_common: any
  core_designsystem: any
  core_domain: any
  core_model: any
  core_ui: any
  flutter:
    sdk: flutter
  flutter_hooks: 0.20.5
  flutter_localizations:
    sdk: flutter
  hooks_riverpod: 2.6.1
  intl: 0.19.0
  lottie: 3.3.1

dev_dependencies:
  build_runner: 2.4.14
  flutter_gen_runner: 5.8.0
  yumemi_lints: 2.2.0

flutter:
  assets:
    - assets/lottie/

flutter_gen:
  output: lib/src/gen/assets
  assets:
    outputs:
      package_parameter_enabled: true
