name: core_analytics_firebase
description: This package provides functions for analysis.
publish_to: "none"

environment:
  sdk: 3.6.0
  flutter: 3.27.1

resolution: workspace

dependencies:
  core_analytics: any
  core_common: any
  firebase_analytics: 11.3.5
  riverpod: 2.6.1
  riverpod_annotation: 2.6.1

dev_dependencies:
  build_runner: 2.4.14
  riverpod_generator: 2.6.3
  test: 1.25.14
  yumemi_lints: 2.2.0
