name: app_mobile
description: "TOBE Mobile App"
publish_to: "none"
version: 0.0.1+2

environment:
  sdk: 3.6.0
  flutter: 3.27.1

resolution: workspace

dependencies:
  core_analytics_firebase: any
  core_authenticator: any
  core_common: any
  core_database_isar: any
  core_datastore: any
  core_designsystem: any
  core_domain: any
  core_model: any
  core_network: any
  core_ui: any
  cupertino_icons: 1.0.8
  dynamic_color: 1.7.0
  envied: 1.0.1
  feature_auth: any
  feature_debug: any
  feature_feed: any
  feature_home: any
  feature_onboarding: any
  feature_quest: any
  feature_settings: any
  firebase_analytics: 11.3.5
  firebase_auth: 5.3.3
  firebase_core: 3.8.0
  firebase_remote_config: 5.1.5
  flutter:
    sdk: flutter
  flutter_hooks: 0.20.5
  flutter_localizations:
    sdk: flutter
  go_router: 14.6.3
  hooks_riverpod: 2.6.1
  intl: 0.20.1
  isar:
    hosted: https://pub.isar-community.dev/
    version: 4.0.3
  isar_flutter_libs:
    hosted: https://pub.isar-community.dev/
    version: 4.0.3
  package_info_plus: 8.1.2
  path_provider: 2.1.5
  riverpod_annotation: 2.6.1
  shared_preferences: 2.3.5
  url_launcher: 6.3.1

dev_dependencies:
  build_runner: 2.4.14
  envied_generator: 1.0.1
  go_router_builder: 2.7.3
  riverpod_generator: 2.6.3
  yumemi_lints: 2.2.0

flutter:
  uses-material-design: true
