name: core_database
description: This package provides local database operations.
publish_to: "none"

environment:
  sdk: 3.6.0

resolution: workspace

dependencies:
  core_common: any
  core_model: any
  riverpod: 2.6.1
  riverpod_annotation: 2.6.1

dev_dependencies:
  build_runner: 2.4.14
  riverpod_generator: 2.6.4
  yumemi_lints: 2.2.0
