name: core_network
description: This package provides network operations.
publish_to: "none"

environment:
  sdk: 3.6.0

resolution: workspace

dependencies:
  core_authenticator: any
  core_common: any
  core_model: any
  core_network_model: any
  dio: 5.7.0
  freezed_annotation: 2.4.4
  retrofit: 4.4.1
  riverpod_annotation: 2.6.1

dev_dependencies:
  build_runner: 2.4.13
  freezed: 2.5.7
  retrofit_generator: 9.1.5
  riverpod_generator: 2.6.3
  yumemi_lints: 2.2.0
