name: core_database_isar
description: This package provides local database operations using Isar.
publish_to: "none"

environment:
  sdk: 3.6.0

resolution: workspace

dependencies:
  core_common: any
  core_database: any
  core_model: any
  isar:
    hosted: https://pub.isar-community.dev/
    version: 4.0.3
  riverpod_annotation: 2.6.1

dev_dependencies:
  build_runner: 2.4.14
  core_testing: any
  riverpod_generator: 2.6.3
  test: 1.25.14
  yumemi_lints: 2.2.0
