name: app_backend
description: An new Dart Frog application
version: 0.1.0
publish_to: none

environment:
  sdk: 3.6.0

resolution: workspace

dependencies:
  built_value: 8.9.3
  core_network_model: any
  dart_frog: 1.2.0
  dotenv: 4.2.0
  ferry: 0.16.1+2
  gql_code_builder: 0.13.0
  gql_error_link: 1.0.0+1
  gql_exec: 1.0.0+1
  gql_http_link: 1.1.0
  gql_link: 1.0.0+1
  gql_transform_link: 1.0.0
  shelf_cors_headers: 0.1.5

dev_dependencies:
  build_runner: 2.4.14
  ferry_generator: 0.12.0
  mocktail: 1.0.4
  test: 1.25.14
  yumemi_lints: 2.2.0
