name: core_designsystem
description: This package provides style definitions, themes, etc.
publish_to: "none"

environment:
  sdk: 3.6.0
  flutter: 3.27.1

resolution: workspace

dependencies:
  core_common: any
  flutter:
    sdk: flutter
  flutter_adaptive_scaffold: 0.3.1
  flutter_localizations:
    sdk: flutter
  flutter_svg: 2.0.17
  gap: 3.0.1
  intl: 0.19.0

dev_dependencies:
  build_runner: 2.4.14
  core_testing: any
  flutter_gen_runner: 5.8.0
  flutter_test:
    sdk: flutter
  yumemi_lints: 2.2.0

flutter:
  assets:
    - assets/images/

flutter_gen:
  output: lib/src/gen/assets
  assets:
    outputs:
      package_parameter_enabled: true
