name: core_testing
description: This package provides convenience functions for testing, etc.
publish_to: "none"

environment:
  sdk: 3.6.0

resolution: workspace

dependencies:
  core_common: any
  core_model: any
  mocktail: 1.0.4
  riverpod: 2.6.1

dev_dependencies:
  yumemi_lints: 2.2.0
