name: app_catalog
description: "TOBE Catalog"
publish_to: "none"
version: 1.0.0

environment:
  sdk: 3.6.0
  flutter: 3.27.1

resolution: workspace

dependencies:
  core_designsystem: any
  core_model: any
  core_ui: any
  cupertino_icons: 1.0.8
  dynamic_color: 1.7.0
  feature_auth: any
  feature_feed: any
  feature_home: any
  feature_onboarding: any
  feature_quest: any
  feature_settings: any
  flutter:
    sdk: flutter
  flutter_riverpod: 2.6.1
  widgetbook: 3.10.2
  widgetbook_annotation: 3.2.0

dev_dependencies:
  build_runner: 2.4.14
  widgetbook_generator: 3.9.1
  yumemi_lints: 2.2.0

flutter:
  uses-material-design: true
