name: core_ui
description: This package provides a UI that depends on the model class and is used by all packages.
publish_to: "none"

environment:
  sdk: 3.6.0
  flutter: 3.27.1

resolution: workspace

dependencies:
  core_common: any
  core_designsystem: any
  core_model: any
  flutter:
    sdk: flutter
  flutter_hooks: 0.20.5
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: 2.6.1
  freezed_annotation: 2.4.4
  intl: 0.19.0
  riverpod: 2.6.1
  riverpod_annotation: 2.6.1

dev_dependencies:
  build_runner: 2.4.14
  core_testing: any
  flutter_test:
    sdk: flutter
  freezed: 2.5.7
  riverpod_generator: 2.6.3
  yumemi_lints: 2.2.0

flutter:
