name: feature_quest
description: "This package provides quest features."
publish_to: "none"

environment:
  sdk: 3.6.0
  flutter: 3.27.1

resolution: workspace

dependencies:
  core_common: any
  core_designsystem: any
  core_domain: any
  core_model: any
  core_ui: any
  flutter:
    sdk: flutter
  flutter_hooks: 0.20.5
  flutter_localizations:
    sdk: flutter
  freezed_annotation: 2.4.4
  hooks_riverpod: 2.6.1
  intl: 0.20.1
  riverpod_annotation: 2.6.1

dev_dependencies:
  build_runner: 2.4.14
  core_testing: any
  flutter_test:
    sdk: flutter
  freezed: 2.5.7
  riverpod_generator: 2.6.4
  yumemi_lints: 2.2.0

flutter:
