name: core_domain
description: This package provides use cases and domain models.
publish_to: "none"

environment:
  sdk: 3.6.0

resolution: workspace

dependencies:
  core_authenticator: any
  core_common: any
  core_data: any
  core_model: any
  riverpod: 2.6.1
  riverpod_annotation: 2.6.1

dev_dependencies:
  build_runner: 2.4.14
  core_testing: any
  riverpod_generator: 2.6.3
  test: 1.25.14
  yumemi_lints: 2.2.0
